services:
  web:
    build: .
    container_name: rails
    image: rails
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis
      DATABASE_HOST: db
      DATABASE_USERNAME: mysql
      DATABASE_PASSWORD: mysql
    links:
      - smtp
      - db
    networks:
      - rails-network
    depends_on:
      - db
      - redis

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - rails-network

  smtp:
    image: sj26/mailcatcher
    container_name: mailcatcher
    restart: always
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - rails-network
    depends_on:
      - redis
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    networks:
    - rails-network
    ports:
    - "3306:3306"

networks:
  rails-network:
    name: rails-network
    driver: bridge
volumes:
  db_data:
    name: db_data